name: Test CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependenceies
      run: |
        sudo apt-get update
        sudo apt install iputils-ping

    - name: Ping
      run: ping ccr.ccs.tencentyun.com -c 5
